- name: Base packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Docker GPG kulcs könyvtárának létrehozása
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Docker GPG kulcs letöltése
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Docker tároló hozzáadása (biztonságos módon)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker engine and components
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Gitea stack mappa létrehozása az /opt alatt
  file:
    path: /opt/gitea-stack
    state: directory
    mode: '0755'
  when: deploy_gitea | default(false) | bool

- name: Docker Compose fájl generálása a Jinja sablonból
  template:
    src: docker-compose-gitea.yml.j2
    dest: /opt/gitea-stack/docker-compose.yml
    mode: '0644'
  when: deploy_gitea | default(false) | bool

- name: Gitea Docker Compose stack elindítása
  community.docker.docker_compose_v2:
    project_src: /opt/gitea-stack
    state: present
  when: deploy_gitea | default(false) | bool

- name: n8n stack főmappa létrehozása az /opt alatt
  file:
    path: /opt/n8n-stack
    state: directory
    mode: '0755'
  when: deploy_n8n | default(false) | bool

- name: n8n adatmappa létrehozása a megfelelő node UID/GID-vel (Jogosultság fix)
  file:
    path: /opt/n8n-stack/n8n-data
    state: directory
    owner: '1000'
    group: '1000'
    mode: '0775'
  when: deploy_n8n | default(false) | bool

- name: n8n Docker Compose fájl generálása a Jinja sablonbóll
  template:
    src: docker-compose-n8n.yml.j2
    dest: /opt/n8n-stack/docker-compose.yml
    mode: '0644'
  when: deploy_n8n | default(false) | bool

- name: n8n Docker Compose stack elindítása
  community.docker.docker_compose_v2:
    project_src: /opt/n8n-stack
    state: present
    recreate: always
  when: deploy_n8n | default(false) | bool