version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: "Default task"
    cmds:
      - task -l
  mac-route:
    desc: "Add a route on macOS"
    cmds:
      - sudo route add -host 192.168.0.2 192.168.0.1
  list-ansible-tags:
    desc: "List Ansible tags"
    cmds:
      - ansible-playbook ansible/setup.yml --list-tags
  asus-prep:
    desc: "Run Ansible playbook for ASUS setup"
    cmds:
      - ansible-playbook -i ansible/inventories/asus ansible/setup.yml --tags prep -k -u root
  asus-nvidia-setup:
    desc: "Run Ansible playbook for ASUS NVIDIA setup"
    cmds:
      - ansible-playbook -i ansible/inventories/asus ansible/setup.yml --tags init-nvidia -k -u root
  kgn:
    desc: "Use kubectl with k0s kubeconfig"
    cmds:
      - kubectl --kubeconfig=./ansible/k0s_kubeconfig get nodes
  kgpa:
    desc: "Use kubectl with k0s kubeconfig"
    cmds:
      - kubectl --kubeconfig=./ansible/k0s_kubeconfig get pods -A
  fix-kubeconfig:
    desc: "Fix kubeconfig server ip"
    cmds:
      - yq e '.clusters[0].cluster.server = "https://192.168.0.2:6443"' -i ansible/k0s_kubeconfig
  grafana-helm-chart:
    desc: "Add Grafana Helm chart repository and search for charts"
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts
      - helm search repo grafana