- name: Setup servers
  hosts: all
  gather_facts: true
  roles:
    - role: init-server
      tags: init-server
    - role: init-docker
      tags: init-docker
    - role: init-k0s
      tags: init-k0s
    - role: init-nvidia
      tags: init-nvidia
  tags: prep
